# Generated by Django 5.2.4 on 2025-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('role', models.TextField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=50)),
            ],
        ),
    ]
