# Generated by Django 5.2.4 on 2025-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=100, null=True)),
                ('skill2', models.CharField(max_length=100, null=True)),
                ('skill3', models.CharField(max_length=100, null=True)),
                ('skill4', models.CharField(max_length=100, null=True)),
                ('skill5', models.CharField(max_length=100, null=True)),
                ('skill6', models.CharField(max_length=100, null=True)),
                ('skill7', models.CharField(max_length=100, null=True)),
                ('skill8', models.CharField(max_length=100, null=True)),
                ('skill9', models.CharField(max_length=100, null=True)),
                ('skill10', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
