# Generated by Django 5.2.4 on 2025-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill12',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
