# Generated by Django 5.2.4 on 2025-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='resume_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
