# Generated by Django 5.2.4 on 2025-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education_resume_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resume_desc',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
